FROM nginx:latest

LABEL maintainer="d2f.working@gmail.com"
LABEL description="NGINX reverse proxy"

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost/ || exit 1

CMD ["nginx", "-g", "daemon off;"]