# Use MongoDB 4.4 instead of latest
FROM mongo:4.4

# Set working directory (optional)
WORKDIR /app

# Copy the init-mongo.js script
COPY ./init-mongo.js /docker-entrypoint-initdb.d/init-mongo.js

# Copy the CSV data
COPY ./data /data

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=example
ENV MONGO_INITDB_DATABASE=recommendation_system

# Expose the MongoDB default port
EXPOSE 27017

# No need for custom CMD; default entrypoint works fine